---
title: "so_web_scrape"
author: "Santiago Torres"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(rvest)
library(jsonlite)
library(tidyverse)
library(mongolite)
library(DBI)
source(here("alec", "skills_extraction.R"))
source(here("insert_esmi.R"))
```

# PoC


```{r parse-jobs}
so_urls <- read_csv("so_urls.csv")

parse_jobs <- function(url) {
  so_html <- read_html(url)

  job <- so_html %>% html_elements("script[type*=ld]") # select only script that contains json job data
  
  job_details <- job %>% html_text2() %>% parse_json()
  
  
  job_title <- job_details$title
  skills <- unlist(job_details$skills)
  description <- job_details$description %>% str_replace_all("\\<.*?\\>", " ") %>% str_replace_all("&bull;", "") %>% trimws()
  state <- job_details$jobLocation 
  state <- state[[1]][2]
  state <- state[[1]]
  state <- state[3] %>% as.character()
  country <- job_details$jobLocation 
  country <- country[[1]][2]
  country <- country[[1]]
  country <- country[2] %>% as.character()
  employment_type <- job_details$employmentType
  company_name <-job_details$hiringOrganization$name
  
  
  company_url <- job_details$hiringOrganization$sameAs
  
  if (is.null(company_url)) {
     company_url <- as.character(NA)}
  
  min_salary <- job_details$baseSalary$value$minValue
  
  if (is.null(min_salary)) {
     min_salary <- as.integer(NA)}
  
  max_salary <- job_details$baseSalary$value$maxValue
  
    if (is.null(max_salary)) {
     max_salary <- as.integer(NA)}

  
  job_skills <- tribble(~job_title,~skills,~description,~state,~country,~employment_type,~company_name,~company_url,~min_salary,~max_salary,
                    job_title,skills,description,state,country,employment_type,company_name,company_url, min_salary, max_salary)
  # output path
  json_path <- here("stack_overflow", "job_jsons", str_c(company_name, job_title, ".json"))
  write_json(job_details, json_path)
  return(job_skills)
}
```

```{r job-skills}
job_skills <- lapply(so_urls$url, parse_jobs) #parse all jobs

job_skills <- bind_rows(job_skills)


write_json(job_skills, "stackoverflow_jobs_mongodb.json")

long_job_skills <- job_skills %>% unnest(skills)

write.csv(long_job_skills, file = "stackoverflow_jobs.csv",
          row.names = FALSE)
```


```{r emsi-skill-extraction}
client_id <- key_list("EMSI")[1,2]
secret <- key_get("EMSI", client_id)
scope <- "emsi_open"

access_token <- get_token(client_id,secret,scope)

all_skills_df <- get_dataset_skills(job_skills, "0.4",access_token)

original_source = "stack_overflow"
all_skills_df <- all_skills_df %>% add_column(original_source)

write.csv(all_skills_df, file= "stackoverflow_jobs_emsi.csv", row.names = FALSE)

```


```{r MariaDB}
db_connection <- dbConnect(RMariaDB::MariaDB(),
                          host=Sys.getenv("TEAMTIDY_DB_HOST"),
                         user = Sys.getenv("TEAMTIDY_DB_USER"),
                        password = Sys.getenv("TEAMTIDY_DB_PASS"),
                       dbname = 'data_science_jobs')


insert_esmi_data(all_skills_df, db_connection)

skills <- dbGetQuery(db_connection, "SELECT * FROM skill")
total_jobs <- dbGetQuery(db_connection, "SELECT * FROM job")

skills %>% group_by(description) %>% summarize(count = n()) %>% arrange(desc(count))
dbDisconnect()

```



```{r mongo-db}
connection_string = 'mongodb+srv://dbUser:Q47Ev1vZU8oEUGxF@cluster0.yvrzo.mongodb.net/test'
trips_collection = mongo(collection="trips", db="jobs", url=connection_string, verbose = TRUE)
trips_collection$count()

connection_string = 'mongodb+srv://dbUser:Q47Ev1vZU8oEUGxF@cluster0.yvrzo.mongodb.net/test'

connection_string = 'mongodb+srv://dbUser:Q47Ev1vZU8oEUGxF@cluster0.yvrzo.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'

trips_collection$iterate()$one()

trips_collection$find(sort = '{"tripduration" : -1}' , limit = 5, fields = '{"_id" : true, "tripduration" : true}')

query = trips_collection$find('{"usertype":"Subscriber","tripduration":{"$gt":500},"$expr": {"$eq": ["$start station name","$end station name"]}}')

nrow(query)

user_types = trips_collection$aggregate('[{"$group":{"_id":"$usertype", "Count": {"$sum":1}}}]')

df <- as.data.frame(user_types)

ggplot(df,aes(x=reorder(`_id`,Count),y=Count))+
  geom_bar(stat="identity",color='yellow',fill='#FFC300')+geom_text(aes(label = Count), color = "red") +coord_flip()+xlab("User Type")


Q47Ev1vZU8oEUGxF

my_collection = mongo(collection = "jobs", db = "DataScience", url=connection_string) # create connection, database and collection

my_collection$insert(job_skills)
```